### PR TITLE
Make: fix make distcheck

### PR DESCRIPTION
**Pull request by jschmidb**
The ecdsa_test.h file was missing in the EXTRA_DIST list.

### CODE REVIEW

**Comment by ifranzki** [comment]
In Opencryptoki we add such headers to `noinst_HEADERS`. Still maybe not 100% as suggested by autoconf, but probably better than `EXTRA_DIST`. Can you maybe give it a try if changing this to the following would work?

```
EXTRA_DIST = testdata 
noinst_HEADERS = testcase.h rsa_test.h aes_gcm_test.h ecdsa1_test.sh \
sha2_test.sh ecdh1_test.sh ecdsa2_test.sh ecdh2_test.sh ecdsa_test.h eddsa_test.h \
drbg_birthdays_test.pl sha3_test.sh ec_keygen1_test.sh ec_keygen2_test.sh \
rsa_keygen2048_test.sh rsa_keygen1024_test.sh rsa_keygen4096_test.sh \
rsa_keygen3072_test.sh rsa_keygen_test.sh icastats_test.c.in icastats_test.sh
```

**Comment by jschmidb** [comment]
Cool, this works as well. Pushing the change in a min ...

**Comment by jschmidb** [comment]
Done.

**Review by ifranzki — APPROVED** [review]

**Review by holger-dengler — CHANGES_REQUESTED** [review]
`noinst_HEADERS` should only contain header files, no scripts. Please use `dist_check_SCRIPTS` for all the scripts.

**Comment by jschmidb** [comment]
ok ... where should I put the icastats_test.c.in ? Also to dist_check_SCRIPTS?

**Comment by holger-dengler** [comment]
Sorry, I missed that one. `icastats_test.c.in` is IMHO another candicate for EXTRA_DIST.

**Comment by jschmidb** [comment]
Thanks! Just re-pushed the change.

**Comment by ifranzki** [comment]
Looks even better now.

**Review by holger-dengler — APPROVED** [review]
Looks good now.

**Pull request merged**
