### PR TITLE
Add missing -pthread flag.

### PR DESCRIPTION
**Pull request by xnox**
Signed-off-by: Dimitri John Ledkov <xnox@ubuntu.com>

### CODE REVIEW

**Comment by p-steuer** [comment]
better add -pthread this to compiler flags, no ?

**Comment by xnox** [comment]
Doesn't it actually need to be in both, or at least in ldflags to trigger linking with pthreads, no?!

**Comment by p-steuer** [comment]
I agree it should be used in both linking, compiling and preprocessing.

My understanding is that when using gcc with its pthread option (see gcc(3)), the flag will be used for preprocesser, compiler and linker.

**Comment by p-steuer** [comment]
If i add it to CFLAGS, the flag is used with libtools link and compile mode.
So i ll merge https://github.com/opencryptoki/libica/pull/32 instead of this one if there are no objections.

**Comment by p-steuer** [comment]
PR https://github.com/opencryptoki/libica/pull/32 was merged. closing this one.

**Pull request closed without merging**
